const createUnformattedData = {
  process: "Process for Edit",
  subprocess: [
    {
      id: 1750937196391,
      subprocess_no: 1,
      subprocess_name: "Sub1",
      steps: [
        {
          id: 1750937205480,
          step_no: 1,
          step_type: "import",
          connection_id: "4",
          destination_connection_id: "5",
          source_tables: [],
          destination_tables: [
            "psl_nonpsl_accounts",
            "reg_product_master",
            "jfs_cbs_dump",
            "exception_master",
            "npa_auto_tech_write_off",
            "npa_auto_securatization_risk",
          ],
          selected_tables: [
            {
              table_name: "exception_master",
              schema_name: "public",
            },
            {
              table_name: "npa_auto_tech_write_off",
              schema_name: "public",
            },
          ],
          pq_description: "",
          pq_query: [],
          ex_description: "",
          ex_query: [],
          source_details: {
            connection_name: "Source Connection",
            server_name: "localhost",
            port_number: 5432,
            database_type: "PostgreSQL",
            database_name: "JanaBank",
            username: "postgres",
          },
          destination_details: {
            connection_name: "Destination Connection",
            server_name: "localhost",
            port_number: 5432,
            database_type: "PostgreSQL",
            database_name: "DestinationDB",
            username: "postgres",
          },
          create_table: [
            {
              table_name: "exception_master",
              schema_name: "public",
              dest_schema_name: "source_schema",
              is_table_exist: true,
            },
            {
              table_name: "npa_auto_tech_write_off",
              schema_name: "public",
              dest_schema_name: "source_schema",
              is_table_exist: true,
            },
          ],
        },
        {
          id: 1750937206789,
          step_no: 2,
          step_type: "process-query",
          connection_id: "5",
          destination_connection_id: "",
          source_tables: [],
          destination_tables: [],
          selected_tables: [],
          pq_description: "Subprocess 1 description",
          pq_query: ["Subprocess 1 query"],
          ex_description: "",
          ex_query: [],
          source_details: {
            connection_name: "Destination Connection",
            server_name: "localhost",
            port_number: 5432,
            database_type: "PostgreSQL",
            database_name: "DestinationDB",
            username: "postgres",
          },
          destination_details: null,
          create_table: [],
        },
        {
          id: 1750937207737,
          step_no: 3,
          step_type: "export",
          connection_id: "4",
          destination_connection_id: "",
          source_tables: [],
          destination_tables: [],
          selected_tables: [],
          pq_description: "",
          pq_query: [],
          ex_description: "export description",
          ex_query: ["ex query1", "ex query2"],
          source_details: {
            connection_name: "Source Connection",
            server_name: "localhost",
            port_number: 5432,
            database_type: "PostgreSQL",
            database_name: "JanaBank",
            username: "postgres",
          },
          destination_details: null,
          create_table: [],
        },
      ],
    },
    {
      id: 1750937197713,
      subprocess_no: 2,
      subprocess_name: "Sub2",
      steps: [
        {
          id: 1750937300415,
          step_no: 1,
          step_type: "process-query",
          connection_id: "6",
          destination_connection_id: "",
          source_tables: [],
          destination_tables: [],
          selected_tables: [],
          pq_description: "Subprocess 2 description",
          pq_query: ["Subprocess 2 query"],
          ex_description: "",
          ex_query: [],
          source_details: {
            connection_name: "Reporting Clone Connection",
            server_name: "localhost",
            port_number: 5432,
            database_type: "PostgreSQL",
            database_name: "reportingtool",
            username: "postgres",
          },
          destination_details: null,
          create_table: [],
        },
      ],
    },
  ],
};

const createFormattedData = {
  process: {
    p_inserted_by: 1,
    p_modified_by: 1,
    p_process_name: "Process for Edit",
    p_process_version: 1,
    p_rerun: true,
  },
  subprocesses: [
    {
      subprocess_data: {
        p_inserted_by: 1,
        p_modified_by: 1,
        p_sub_process_order: 1,
        p_sub_process_name: "Sub1",
      },
      steps: [
        {
          steps: {
            p_inserted_by: 1,
            p_modified_by: 1,
            p_process_step_order: 1,
            p_process_step_action: "import",
            p_source_conn_id: 4,
            p_dest_conn_id: 5,
          },
          create_table: [
            {
              table_name: "exception_master",
              source_schema_name: "public",
              dest_schema_name: "source_schema",
              is_table_exist: true,
            },
            {
              table_name: "npa_auto_tech_write_off",
              source_schema_name: "public",
              dest_schema_name: "source_schema",
              is_table_exist: true,
            },
          ],
          table_config: [
            [
              {
                p_inserted_by: 1,
                p_modified_by: 1,
                p_connection_name: "Source Connection",
                p_database_name: "JanaBank",
                p_schema_name: "public",
                p_table_name: "exception_master",
                p_is_temp_table: false,
                p_table_type: "source",
                p_table_category: "import",
                p_is_upsert: false,
              },
              {
                p_inserted_by: 1,
                p_modified_by: 1,
                p_connection_name: "Destination Connection",
                p_database_name: "DestinationDB",
                p_schema_name: "source_schema",
                p_table_name: "exception_master",
                p_is_temp_table: false,
                p_table_type: "destination",
                p_table_category: "import",
                p_is_upsert: true,
              },
            ],
            [
              {
                p_inserted_by: 1,
                p_modified_by: 1,
                p_connection_name: "Source Connection",
                p_database_name: "JanaBank",
                p_schema_name: "public",
                p_table_name: "npa_auto_tech_write_off",
                p_is_temp_table: false,
                p_table_type: "source",
                p_table_category: "import",
                p_is_upsert: false,
              },
              {
                p_inserted_by: 1,
                p_modified_by: 1,
                p_connection_name: "Destination Connection",
                p_database_name: "DestinationDB",
                p_schema_name: "source_schema",
                p_table_name: "npa_auto_tech_write_off",
                p_is_temp_table: false,
                p_table_type: "destination",
                p_table_category: "import",
                p_is_upsert: true,
              },
            ],
          ],
          table_config_details: [
            [
              [
                {
                  p_inserted_by: 1,
                  p_modified_by: 1,
                  p_column_name: "row_id",
                  p_datatype: "numeric",
                  p_length: null,
                  p_precision: 10,
                  p_scale: 0,
                  p_is_primary_key: false,
                  p_isautogenerated: "NO",
                  p_ordinal_position: 1,
                  p_nullable: "NO",
                },
                {
                  p_inserted_by: 1,
                  p_modified_by: 1,
                  p_column_name: "account_number",
                  p_datatype: "numeric",
                  p_length: null,
                  p_precision: 20,
                  p_scale: 0,
                  p_is_primary_key: false,
                  p_isautogenerated: "NO",
                  p_ordinal_position: 2,
                  p_nullable: "YES",
                },
                {
                  p_inserted_by: 1,
                  p_modified_by: 1,
                  p_column_name: "cbs_restructured_date",
                  p_datatype: "character varying",
                  p_length: 40,
                  p_precision: null,
                  p_scale: null,
                  p_is_primary_key: false,
                  p_isautogenerated: "NO",
                  p_ordinal_position: 3,
                  p_nullable: "YES",
                },
                {
                  p_inserted_by: 1,
                  p_modified_by: 1,
                  p_column_name: "cm_accrual",
                  p_datatype: "character varying",
                  p_length: 2,
                  p_precision: null,
                  p_scale: null,
                  p_is_primary_key: false,
                  p_isautogenerated: "NO",
                  p_ordinal_position: 4,
                  p_nullable: "YES",
                },
                {
                  p_inserted_by: 1,
                  p_modified_by: 1,
                  p_column_name: "npa_date",
                  p_datatype: "timestamp without time zone",
                  p_length: null,
                  p_precision: null,
                  p_scale: null,
                  p_is_primary_key: false,
                  p_isautogenerated: "NO",
                  p_ordinal_position: 5,
                  p_nullable: "YES",
                },
                {
                  p_inserted_by: 1,
                  p_modified_by: 1,
                  p_column_name: "business_date",
                  p_datatype: "timestamp without time zone",
                  p_length: null,
                  p_precision: null,
                  p_scale: null,
                  p_is_primary_key: false,
                  p_isautogenerated: "NO",
                  p_ordinal_position: 6,
                  p_nullable: "YES",
                },
              ],
              [
                {
                  p_inserted_by: 1,
                  p_modified_by: 1,
                  p_column_name: "row_id",
                  p_datatype: "numeric",
                  p_length: null,
                  p_precision: 10,
                  p_scale: 0,
                  p_is_primary_key: false,
                  p_isautogenerated: "NO",
                  p_ordinal_position: 1,
                  p_nullable: "NO",
                },
                {
                  p_inserted_by: 1,
                  p_modified_by: 1,
                  p_column_name: "account_number",
                  p_datatype: "numeric",
                  p_length: null,
                  p_precision: 20,
                  p_scale: 0,
                  p_is_primary_key: false,
                  p_isautogenerated: "NO",
                  p_ordinal_position: 2,
                  p_nullable: "YES",
                },
                {
                  p_inserted_by: 1,
                  p_modified_by: 1,
                  p_column_name: "cbs_restructured_date",
                  p_datatype: "character varying",
                  p_length: 40,
                  p_precision: null,
                  p_scale: null,
                  p_is_primary_key: false,
                  p_isautogenerated: "NO",
                  p_ordinal_position: 3,
                  p_nullable: "YES",
                },
                {
                  p_inserted_by: 1,
                  p_modified_by: 1,
                  p_column_name: "cm_accrual",
                  p_datatype: "character varying",
                  p_length: 2,
                  p_precision: null,
                  p_scale: null,
                  p_is_primary_key: false,
                  p_isautogenerated: "NO",
                  p_ordinal_position: 4,
                  p_nullable: "YES",
                },
                {
                  p_inserted_by: 1,
                  p_modified_by: 1,
                  p_column_name: "npa_date",
                  p_datatype: "timestamp without time zone",
                  p_length: null,
                  p_precision: null,
                  p_scale: null,
                  p_is_primary_key: false,
                  p_isautogenerated: "NO",
                  p_ordinal_position: 5,
                  p_nullable: "YES",
                },
                {
                  p_inserted_by: 1,
                  p_modified_by: 1,
                  p_column_name: "business_date",
                  p_datatype: "timestamp without time zone",
                  p_length: null,
                  p_precision: null,
                  p_scale: null,
                  p_is_primary_key: false,
                  p_isautogenerated: "NO",
                  p_ordinal_position: 6,
                  p_nullable: "YES",
                },
              ],
            ],
            [
              [
                {
                  p_inserted_by: 1,
                  p_modified_by: 1,
                  p_column_name: "row_id",
                  p_datatype: "numeric",
                  p_length: null,
                  p_precision: 38,
                  p_scale: 0,
                  p_is_primary_key: false,
                  p_isautogenerated: "NO",
                  p_ordinal_position: 1,
                  p_nullable: "NO",
                },
                {
                  p_inserted_by: 1,
                  p_modified_by: 1,
                  p_column_name: "createddate",
                  p_datatype: "timestamp without time zone",
                  p_length: null,
                  p_precision: null,
                  p_scale: null,
                  p_is_primary_key: false,
                  p_isautogenerated: "NO",
                  p_ordinal_position: 2,
                  p_nullable: "YES",
                },
                {
                  p_inserted_by: 1,
                  p_modified_by: 1,
                  p_column_name: "account_number",
                  p_datatype: "character varying",
                  p_length: 255,
                  p_precision: null,
                  p_scale: null,
                  p_is_primary_key: false,
                  p_isautogenerated: "NO",
                  p_ordinal_position: 3,
                  p_nullable: "YES",
                },
                {
                  p_inserted_by: 1,
                  p_modified_by: 1,
                  p_column_name: "write_off_month",
                  p_datatype: "character varying",
                  p_length: 255,
                  p_precision: null,
                  p_scale: null,
                  p_is_primary_key: false,
                  p_isautogenerated: "NO",
                  p_ordinal_position: 4,
                  p_nullable: "YES",
                },
              ],
              [
                {
                  p_inserted_by: 1,
                  p_modified_by: 1,
                  p_column_name: "row_id",
                  p_datatype: "numeric",
                  p_length: null,
                  p_precision: 38,
                  p_scale: 0,
                  p_is_primary_key: false,
                  p_isautogenerated: "NO",
                  p_ordinal_position: 1,
                  p_nullable: "NO",
                },
                {
                  p_inserted_by: 1,
                  p_modified_by: 1,
                  p_column_name: "createddate",
                  p_datatype: "timestamp without time zone",
                  p_length: null,
                  p_precision: null,
                  p_scale: null,
                  p_is_primary_key: false,
                  p_isautogenerated: "NO",
                  p_ordinal_position: 2,
                  p_nullable: "YES",
                },
                {
                  p_inserted_by: 1,
                  p_modified_by: 1,
                  p_column_name: "account_number",
                  p_datatype: "character varying",
                  p_length: 255,
                  p_precision: null,
                  p_scale: null,
                  p_is_primary_key: false,
                  p_isautogenerated: "NO",
                  p_ordinal_position: 3,
                  p_nullable: "YES",
                },
                {
                  p_inserted_by: 1,
                  p_modified_by: 1,
                  p_column_name: "write_off_month",
                  p_datatype: "character varying",
                  p_length: 255,
                  p_precision: null,
                  p_scale: null,
                  p_is_primary_key: false,
                  p_isautogenerated: "NO",
                  p_ordinal_position: 4,
                  p_nullable: "YES",
                },
              ],
            ],
          ],
          table_mapping: [
            [
              {
                p_inserted_by: 1,
                p_modified_by: 1,
                p_source_conn_id: 4,
                p_source_db: "JanaBank",
                p_source_schema: "public",
                p_source_table: "exception_master",
                p_source_column: "row_id",
                p_source_data_type: "numeric",
                p_dest_conn_id: 5,
                p_dest_db: "DestinationDB",
                p_dest_schema: "source_schema",
                p_dest_table: "exception_master",
                p_dest_column: "row_id",
                p_dest_data_type: "numeric",
                p_ordinal_position: 1,
              },
              {
                p_inserted_by: 1,
                p_modified_by: 1,
                p_source_conn_id: 4,
                p_source_db: "JanaBank",
                p_source_schema: "public",
                p_source_table: "exception_master",
                p_source_column: "account_number",
                p_source_data_type: "numeric",
                p_dest_conn_id: 5,
                p_dest_db: "DestinationDB",
                p_dest_schema: "source_schema",
                p_dest_table: "exception_master",
                p_dest_column: "account_number",
                p_dest_data_type: "numeric",
                p_ordinal_position: 2,
              },
              {
                p_inserted_by: 1,
                p_modified_by: 1,
                p_source_conn_id: 4,
                p_source_db: "JanaBank",
                p_source_schema: "public",
                p_source_table: "exception_master",
                p_source_column: "cbs_restructured_date",
                p_source_data_type: "character varying",
                p_dest_conn_id: 5,
                p_dest_db: "DestinationDB",
                p_dest_schema: "source_schema",
                p_dest_table: "exception_master",
                p_dest_column: "cbs_restructured_date",
                p_dest_data_type: "character varying",
                p_ordinal_position: 3,
              },
              {
                p_inserted_by: 1,
                p_modified_by: 1,
                p_source_conn_id: 4,
                p_source_db: "JanaBank",
                p_source_schema: "public",
                p_source_table: "exception_master",
                p_source_column: "cm_accrual",
                p_source_data_type: "character varying",
                p_dest_conn_id: 5,
                p_dest_db: "DestinationDB",
                p_dest_schema: "source_schema",
                p_dest_table: "exception_master",
                p_dest_column: "cm_accrual",
                p_dest_data_type: "character varying",
                p_ordinal_position: 4,
              },
              {
                p_inserted_by: 1,
                p_modified_by: 1,
                p_source_conn_id: 4,
                p_source_db: "JanaBank",
                p_source_schema: "public",
                p_source_table: "exception_master",
                p_source_column: "npa_date",
                p_source_data_type: "timestamp without time zone",
                p_dest_conn_id: 5,
                p_dest_db: "DestinationDB",
                p_dest_schema: "source_schema",
                p_dest_table: "exception_master",
                p_dest_column: "npa_date",
                p_dest_data_type: "timestamp without time zone",
                p_ordinal_position: 5,
              },
              {
                p_inserted_by: 1,
                p_modified_by: 1,
                p_source_conn_id: 4,
                p_source_db: "JanaBank",
                p_source_schema: "public",
                p_source_table: "exception_master",
                p_source_column: "business_date",
                p_source_data_type: "timestamp without time zone",
                p_dest_conn_id: 5,
                p_dest_db: "DestinationDB",
                p_dest_schema: "source_schema",
                p_dest_table: "exception_master",
                p_dest_column: "business_date",
                p_dest_data_type: "timestamp without time zone",
                p_ordinal_position: 6,
              },
            ],
            [
              {
                p_inserted_by: 1,
                p_modified_by: 1,
                p_source_conn_id: 4,
                p_source_db: "JanaBank",
                p_source_schema: "public",
                p_source_table: "npa_auto_tech_write_off",
                p_source_column: "row_id",
                p_source_data_type: "numeric",
                p_dest_conn_id: 5,
                p_dest_db: "DestinationDB",
                p_dest_schema: "source_schema",
                p_dest_table: "npa_auto_tech_write_off",
                p_dest_column: "row_id",
                p_dest_data_type: "numeric",
                p_ordinal_position: 1,
              },
              {
                p_inserted_by: 1,
                p_modified_by: 1,
                p_source_conn_id: 4,
                p_source_db: "JanaBank",
                p_source_schema: "public",
                p_source_table: "npa_auto_tech_write_off",
                p_source_column: "createddate",
                p_source_data_type: "timestamp without time zone",
                p_dest_conn_id: 5,
                p_dest_db: "DestinationDB",
                p_dest_schema: "source_schema",
                p_dest_table: "npa_auto_tech_write_off",
                p_dest_column: "createddate",
                p_dest_data_type: "timestamp without time zone",
                p_ordinal_position: 2,
              },
              {
                p_inserted_by: 1,
                p_modified_by: 1,
                p_source_conn_id: 4,
                p_source_db: "JanaBank",
                p_source_schema: "public",
                p_source_table: "npa_auto_tech_write_off",
                p_source_column: "account_number",
                p_source_data_type: "character varying",
                p_dest_conn_id: 5,
                p_dest_db: "DestinationDB",
                p_dest_schema: "source_schema",
                p_dest_table: "npa_auto_tech_write_off",
                p_dest_column: "account_number",
                p_dest_data_type: "character varying",
                p_ordinal_position: 3,
              },
              {
                p_inserted_by: 1,
                p_modified_by: 1,
                p_source_conn_id: 4,
                p_source_db: "JanaBank",
                p_source_schema: "public",
                p_source_table: "npa_auto_tech_write_off",
                p_source_column: "write_off_month",
                p_source_data_type: "character varying",
                p_dest_conn_id: 5,
                p_dest_db: "DestinationDB",
                p_dest_schema: "source_schema",
                p_dest_table: "npa_auto_tech_write_off",
                p_dest_column: "write_off_month",
                p_dest_data_type: "character varying",
                p_ordinal_position: 4,
              },
            ],
          ],
        },
        {
          steps: {
            p_inserted_by: 1,
            p_modified_by: 1,
            p_process_step_order: 2,
            p_process_step_action: "process-query",
            p_process_step_description: "Subprocess 1 description",
            p_process_step_query: ["Subprocess 1 query"],
            p_source_conn_id: 5,
          },
          create_table: [],
          table_config: [],
          table_config_details: [],
          table_mapping: [],
        },
        {
          steps: {
            p_inserted_by: 1,
            p_modified_by: 1,
            p_process_step_order: 3,
            p_process_step_action: "export",
            p_process_step_description: "export description",
            p_process_step_query: ["ex query1", "ex query2"],
            p_source_conn_id: 4,
          },
          create_table: [],
          table_config: [],
          table_config_details: [],
          table_mapping: [],
        },
      ],
    },
    {
      subprocess_data: {
        p_inserted_by: 1,
        p_modified_by: 1,
        p_sub_process_order: 2,
        p_sub_process_name: "Sub2",
      },
      steps: [
        {
          steps: {
            p_inserted_by: 1,
            p_modified_by: 1,
            p_process_step_order: 1,
            p_process_step_action: "process-query",
            p_process_step_description: "Subprocess 2 description",
            p_process_step_query: ["Subprocess 2 query"],
            p_source_conn_id: 6,
          },
          create_table: [],
          table_config: [],
          table_config_details: [],
          table_mapping: [],
        },
      ],
    },
  ],
};


// --------------------------------


// Transform and set subprocesses data
        const transformedSubprocesses = processData.subprocesses.map(
          (sp, spIndex) => ({
            id: sp.subprocess_data.sub_process_id || Date.now() + spIndex,
            sub_process_id: sp.subprocess_data.sub_process_id,
            subprocess_no: sp.subprocess_data.sub_process_order,
            subprocess_name: sp.subprocess_data.sub_process_name,
            steps: sp.steps.map((step, stepIndex) => ({
              id: step.steps.process_step_id || Date.now() + stepIndex,
              process_step_id: step.steps.process_step_id,
              step_no: step.steps.process_step_order,
              step_type: step.steps.process_step_action,
              connection_id: step.steps.source_conn_id?.toString() || "",
              destination_connection_id:
                step.steps.dest_conn_id?.toString() || "",
              source_tables: [],
              destination_tables: [],
              selected_tables: [],
              pq_description: step.steps.process_step_description || "",
              pq_query: step.steps.process_step_query || [],
              ex_description: step.steps.process_step_description || "",
              ex_query: step.steps.process_step_query || [],
              source_details: null,
              destination_details: null,
              create_table:
                step.table_config.map(([first, second]) => ({
                  table_name: first.table_name,
                  source_schema_name: first.schema_name,
                  dest_schema_name: second.schema_name,
                  is_table_exist: true,
                })) || [],
            })),
          })
        );

        // Load mock data instead of API call
          const loadMockData = () => {
            setLoadingData(true);
        
            // Simulate loading delay
            setTimeout(() => {
              try {
                const processData = mockData;
        
                // Set process details
                setProcessName(processData.process.process_name);
                setProcessMasterId(processData.process.process_master_id);
        
                
        
                // Transform and set subprocesses data
                const transformedSubprocesses = processData.subprocesses.map(
                  (sp, spIndex) => ({
                    id: sp.subprocess_data.sub_process_id || Date.now() + spIndex,
                    sub_process_id: sp.subprocess_data.sub_process_id,
                    subprocess_no: sp.subprocess_data.sub_process_order,
                    subprocess_name: sp.subprocess_data.sub_process_name,
                    steps: sp.steps.map((step, stepIndex) => ({
                      id: step.steps.process_step_id || Date.now() + stepIndex,
                      process_step_id: step.steps.process_step_id,
                      step_no: step.steps.process_step_order,
                      step_type: step.steps.process_step_action,
                      connection_id: step.steps.source_conn_id?.toString() || "",
                      destination_connection_id:
                        step.steps.dest_conn_id?.toString() || "",
                      source_tables: [],
                      destination_tables: [],
                      selected_tables: [],
                      pq_description: step.steps.process_step_description || "",
                      pq_query: step.steps.process_step_query || [],
                      ex_description: step.steps.process_step_description || "",
                      ex_query: step.steps.process_step_query || [],
                      source_details: null,
                      destination_details: null,
                      create_table:
                        step.table_config.map(([first, second]) => ({
                          table_name: first.table_name,
                          source_schema_name: first.schema_name,
                          dest_schema_name: second.schema_name,
                          is_table_exist: true,
                        })) || [],
                    })),
                  })
                );
        
                setSubprocesses(transformedSubprocesses);
                // setConnections(mockConnections);
              } catch (error) {
                console.error("Error loading mock data:", error);
                toast({
                  variant: "destructive",
                  title: "Error",
                  description: "Failed to load process data",
                });
              } finally {
                setLoadingData(false);
              }
            }, 500); // Simulate 500ms loading time
          };

