import HomePage from "./home/page";

export default function Home() {
  return <HomePage />;
}

// old implementation

const a1 = 1;

/*
// Helper function to fetch column details for a table
    const fetchColumnDetails = async (connectionId, schemaName, tableName) => {
      try {
        const response = await fetch(
          `${baseURL}/connection-columns?conn_id=${connectionId}&schema_name=${schemaName}&table_name=${tableName}`
        );
        const result = await response.json();

        if (result.status === "success") {
          return result.data.map((column, index) => ({
            p_inserted_by: 1,
            p_modified_by: 1,
            p_column_name: column.column_name,
            p_datatype: column.data_type,
            p_length: column.character_maximum_length,
            p_precision: column.numeric_precision,
            p_scale: column.numeric_scale,
            p_is_primary_key: column.is_primary_key,
            p_isautogenerated: column.is_identity,
            p_ordinal_position: column.ordinal_position,
            p_nullable: column.is_nullable,
          }));
        }
        return [];
      } catch (error) {
        console.error(
          `Error fetching columns for ${schemaName}.${tableName}:`,
          error
        );
        return [];
      }
    };

    // Helper function to create table mappings
    const createTableMappings = async (
      createTableData,
      sourceConnectionId,
      sourceConnectionDetails,
      destinationConnectionId,
      destinationConnectionDetails
    ) => {
      const tableMappings = await Promise.all(
        createTableData.map(
          async ({ schema_name, table_name, dest_schema_name }) => {
            // Fetch source columns
            const sourceColumns = await fetchColumnDetails(
              sourceConnectionId,
              schema_name,
              table_name
            );

            // Fetch destination columns (only if table exists)
            const destColumns = await fetchColumnDetails(
              destinationConnectionId,
              dest_schema_name,
              table_name
            );

            // Create mappings between source and destination columns
            const mappings = sourceColumns.map((sourceCol, index) => {
              // Try to find matching destination column by name or use index-based mapping
              const destCol =
                destColumns.find(
                  (col) =>
                    col.p_column_name.toLowerCase() ===
                    sourceCol.p_column_name.toLowerCase()
                ) ||
                destColumns[index] ||
                destColumns[0]; // Fallback to index or first column

              return {
                p_inserted_by: 1,
                p_modified_by: 1,
                p_source_conn_id: Number(sourceConnectionId),
                p_source_db: sourceConnectionDetails.database_name,
                p_source_schema: schema_name,
                p_source_table: table_name,
                p_source_column: sourceCol.p_column_name,
                p_source_data_type: sourceCol.p_datatype,
                p_dest_conn_id: Number(destinationConnectionId),
                p_dest_db: destinationConnectionDetails.database_name,
                p_dest_schema: dest_schema_name,
                p_dest_table: table_name,
                p_dest_column: destCol
                  ? destCol.p_column_name
                  : sourceCol.p_column_name,
                p_dest_data_type: destCol
                  ? destCol.p_datatype
                  : sourceCol.p_datatype,
                p_ordinal_position: sourceCol.p_ordinal_position,
              };
            });

            return mappings;
          }
        )
      );

      return tableMappings;
    };

    // Main function to format data
    const formatDataWithConfigDetails = async (processName, subprocesses) => {
      const formattedSubprocesses = await Promise.all(
        subprocesses.map(async (sp) => ({
          subprocess_data: {
            p_inserted_by: 1,
            p_modified_by: 1,
            p_sub_process_order: sp.subprocess_no,
            p_sub_process_name: sp.subprocess_name,
          },
          steps: await Promise.all(
            sp.steps.map(async (step) => {
              if (step.step_type === "import") {
                // Use create_table data which contains the complete mapping info
                const createTableData = step.create_table || [];

                // Fetch column details for each table - create duplicates for source and destination
                const tableConfigDetails = await Promise.all(
                  createTableData.flatMap(
                    ({ schema_name, table_name, dest_schema_name }) => [
                      // First entry for source table
                      fetchColumnDetails(
                        step.connection_id,
                        schema_name,
                        table_name
                      ),
                      // Second entry for destination table (or same source table if needed)
                      fetchColumnDetails(
                        step.connection_id,
                        schema_name,
                        table_name
                      ),
                    ]
                  )
                );

                // No need to flatten since we already have the desired structure
                const flattenedConfigDetails = tableConfigDetails;

                // Create table mappings using create_table data
                const tableMappings = await createTableMappings(
                  createTableData,
                  step.connection_id,
                  step.source_details,
                  step.destination_connection_id,
                  step.destination_details
                );

                return {
                  steps: {
                    p_inserted_by: 1,
                    p_modified_by: 1,
                    p_process_step_order: step.step_no,
                    p_process_step_action: step.step_type,
                    p_source_conn_id: Number(step.connection_id),
                    p_dest_conn_id: Number(step.destination_connection_id),
                  },
                  create_table: createTableData.map(
                    ({
                      schema_name,
                      table_name,
                      dest_schema_name,
                      is_table_exist,
                    }) => ({
                      table_name: table_name,
                      source_schema_name: schema_name,
                      dest_schema_name: dest_schema_name,
                      is_table_exist: is_table_exist,
                    })
                  ),
                  table_config: createTableData.map(
                    ({ schema_name, table_name, dest_schema_name }) => [
                      // Source table config
                      {
                        p_inserted_by: 1,
                        p_modified_by: 1,
                        p_connection_name: step.source_details.connection_name,
                        p_database_name: step.source_details.database_name,
                        p_schema_name: schema_name,
                        p_table_name: table_name,
                        p_is_temp_table: false,
                        p_table_type: "source",
                        p_table_category: "import",
                        p_is_upsert: false,
                      },
                      // Destination table config
                      {
                        p_inserted_by: 1,
                        p_modified_by: 1,
                        p_connection_name:
                          step.destination_details.connection_name,
                        p_database_name: step.destination_details.database_name,
                        p_schema_name: dest_schema_name,
                        p_table_name: table_name,
                        p_is_temp_table: false,
                        p_table_type: "destination",
                        p_table_category: "import",
                        p_is_upsert: true,
                      },
                    ]
                  ),
                  table_config_details: flattenedConfigDetails,
                  table_mapping: tableMappings,
                };
              } else if (step.step_type === "process-query") {
                return {
                  steps: {
                    p_inserted_by: 1,
                    p_modified_by: 1,
                    p_process_step_order: step.step_no,
                    p_process_step_action: "process-query",
                    p_process_step_description: step.pq_description,
                    p_process_step_query: step.pq_query,
                    p_source_conn_id: Number(step.connection_id),
                  },
                  create_table: [],
                  table_config: [],
                  table_config_details: [],
                  table_mapping: [],
                };
              } else {
                // Export step
                return {
                  steps: {
                    p_inserted_by: 1,
                    p_modified_by: 1,
                    p_process_step_order: step.step_no,
                    p_process_step_action: "export",
                    p_process_step_description: step.ex_description,
                    p_process_step_query: step.ex_query,
                    p_source_conn_id: Number(step.connection_id),
                  },
                  create_table: [],
                  table_config: [],
                  table_config_details: [],
                  table_mapping: [],
                };
              }
            })
          ),
        }))
      );

      return {
        process: {
          p_inserted_by: 1,
          p_modified_by: 1,
          p_process_name: processName,
          p_process_version: 1,
          p_rerun: true,
        },
        subprocesses: formattedSubprocesses,
      };
    };

    // Usage - simplified parameters since step data now contains all needed info
    const formattedData = await formatDataWithConfigDetails(
      processName,
      subprocesses
    );

    console.log(formattedData);
*/

//temporary data for reference

// Source - 4 (2)
// Destination - 5 (1)
// Clone - 6

const editUnformattedData = {
  process: "Process for Edit",
  subprocess: [
    {
      id: 31,
      sub_process_id: 31,
      subprocess_no: 1,
      subprocess_name: "Sub1",
      steps: [
        {
          id: 69,
          process_step_id: 69,
          step_no: 1,
          step_type: "import",
          connection_id: "4",
          destination_connection_id: "5",
          source_tables: [],
          destination_tables: [],
          selected_tables: [],
          pq_description: "",
          pq_query: [],
          ex_description: "",
          ex_query: [],
          source_details: {
            connection_name: "Source Connection",
            server_name: "localhost",
            port_number: 5432,
            database_type: "PostgreSQL",
            database_name: "JanaBank",
            username: "postgres",
          },
          destination_details: {
            connection_name: "Destination Connection",
            server_name: "localhost",
            port_number: 5432,
            database_type: "PostgreSQL",
            database_name: "DestinationDB",
            username: "postgres",
          },
          create_table: [
            {
              table_name: "exception_master",
              source_schema_name: "public",
              dest_schema_name: "source_schema",
              is_table_exist: true,
            },
            {
              table_name: "npa_auto_tech_write_off",
              source_schema_name: "public",
              dest_schema_name: "source_schema",
              is_table_exist: true,
            },
          ],
        },
        {
          id: 70,
          process_step_id: 70,
          step_no: 2,
          step_type: "process-query",
          connection_id: "5",
          destination_connection_id: "",
          source_tables: [],
          destination_tables: [],
          selected_tables: [],
          pq_description: "Subprocess 1 description",
          pq_query: ["Subprocess 1 query"],
          ex_description: "Subprocess 1 description",
          ex_query: ["Subprocess 1 query"],
          source_details: {
            connection_name: "Destination Connection",
            server_name: "localhost",
            port_number: 5432,
            database_type: "PostgreSQL",
            database_name: "DestinationDB",
            username: "postgres",
          },
          destination_details: null,
          create_table: [],
        },
        {
          id: 71,
          process_step_id: 71,
          step_no: 3,
          step_type: "export",
          connection_id: "4",
          destination_connection_id: "",
          source_tables: [],
          destination_tables: [],
          selected_tables: [],
          pq_description: "export description",
          pq_query: ["ex query1", "ex query2"],
          ex_description: "export description",
          ex_query: ["ex query1", "ex query2"],
          source_details: {
            connection_name: "Source Connection",
            server_name: "localhost",
            port_number: 5432,
            database_type: "PostgreSQL",
            database_name: "JanaBank",
            username: "postgres",
          },
          destination_details: null,
          create_table: [],
        },
      ],
    },
    {
      id: 32,
      sub_process_id: 32,
      subprocess_no: 2,
      subprocess_name: "Sub2",
      steps: [
        {
          id: 72,
          process_step_id: 72,
          step_no: 1,
          step_type: "process-query",
          connection_id: "6",
          destination_connection_id: "",
          source_tables: [],
          destination_tables: [],
          selected_tables: [],
          pq_description: "Subprocess 2 description",
          pq_query: ["Subprocess 2 query"],
          ex_description: "Subprocess 2 description",
          ex_query: ["Subprocess 2 query"],
          source_details: {
            connection_name: "Reporting Clone Connection",
            server_name: "localhost",
            port_number: 5432,
            database_type: "PostgreSQL",
            database_name: "reportingtool",
            username: "postgres",
          },
          destination_details: null,
          create_table: [],
        },
      ],
    },
  ],
};

// -----------------------------------------------------

const editFormattedData = {
    "process": {
        "p_inserted_by": 1,
        "p_modified_by": 1,
        "p_process_master_id": 8,
        "p_process_name": "Process for Edit",
        "p_process_version": 1,
        "p_rerun": true
    },
    "subprocesses": [
        {
            "subprocess_data": {
                "p_inserted_by": 1,
                "p_modified_by": 1,
                "p_process_master_id": 8,
                "p_sub_process_id": 31,
                "p_sub_process_order": 1,
                "p_sub_process_name": "Sub1"
            },
            "steps": [
                {
                    "steps": {
                        "p_inserted_by": 1,
                        "p_modified_by": 1,
                        "p_process_step_id": 69,
                        "p_process_master_id": 8,
                        "p_sub_process_id": 31,
                        "p_process_step_order": 1,
                        "p_process_step_action": "import",
                        "p_source_conn_id": 4,
                        "p_dest_conn_id": 5
                    },
                    "create_table": [
                        {
                            "table_name": "exception_master",
                            "source_schema_name": "public",
                            "dest_schema_name": "source_schema",
                            "is_table_exist": true
                        },
                        {
                            "table_name": "npa_auto_tech_write_off",
                            "source_schema_name": "public",
                            "dest_schema_name": "source_schema",
                            "is_table_exist": true
                        }
                    ],
                    "table_config": [
                        [
                            {
                                "p_inserted_by": 1,
                                "p_modified_by": 1,
                                "p_connection_name": "Source Connection",
                                "p_database_name": "JanaBank",
                                "p_schema_name": "public",
                                "p_table_name": "exception_master",
                                "p_is_temp_table": false,
                                "p_table_type": "source",
                                "p_table_category": "import",
                                "p_is_upsert": false
                            },
                            {
                                "p_inserted_by": 1,
                                "p_modified_by": 1,
                                "p_connection_name": "Destination Connection",
                                "p_database_name": "DestinationDB",
                                "p_schema_name": "source_schema",
                                "p_table_name": "exception_master",
                                "p_is_temp_table": false,
                                "p_table_type": "destination",
                                "p_table_category": "import",
                                "p_is_upsert": true
                            }
                        ],
                        [
                            {
                                "p_inserted_by": 1,
                                "p_modified_by": 1,
                                "p_connection_name": "Source Connection",
                                "p_database_name": "JanaBank",
                                "p_schema_name": "public",
                                "p_table_name": "npa_auto_tech_write_off",
                                "p_is_temp_table": false,
                                "p_table_type": "source",
                                "p_table_category": "import",
                                "p_is_upsert": false
                            },
                            {
                                "p_inserted_by": 1,
                                "p_modified_by": 1,
                                "p_connection_name": "Destination Connection",
                                "p_database_name": "DestinationDB",
                                "p_schema_name": "source_schema",
                                "p_table_name": "npa_auto_tech_write_off",
                                "p_is_temp_table": false,
                                "p_table_type": "destination",
                                "p_table_category": "import",
                                "p_is_upsert": true
                            }
                        ]
                    ],
                    "table_config_details": [
                        [
                            [
                                {
                                    "p_inserted_by": 1,
                                    "p_modified_by": 1,
                                    "p_column_name": "row_id",
                                    "p_datatype": "numeric",
                                    "p_length": null,
                                    "p_precision": 10,
                                    "p_scale": 0,
                                    "p_is_primary_key": false,
                                    "p_isautogenerated": "NO",
                                    "p_ordinal_position": 1,
                                    "p_nullable": "NO"
                                },
                                {
                                    "p_inserted_by": 1,
                                    "p_modified_by": 1,
                                    "p_column_name": "account_number",
                                    "p_datatype": "numeric",
                                    "p_length": null,
                                    "p_precision": 20,
                                    "p_scale": 0,
                                    "p_is_primary_key": false,
                                    "p_isautogenerated": "NO",
                                    "p_ordinal_position": 2,
                                    "p_nullable": "YES"
                                },
                                {
                                    "p_inserted_by": 1,
                                    "p_modified_by": 1,
                                    "p_column_name": "cbs_restructured_date",
                                    "p_datatype": "character varying",
                                    "p_length": 40,
                                    "p_precision": null,
                                    "p_scale": null,
                                    "p_is_primary_key": false,
                                    "p_isautogenerated": "NO",
                                    "p_ordinal_position": 3,
                                    "p_nullable": "YES"
                                },
                                {
                                    "p_inserted_by": 1,
                                    "p_modified_by": 1,
                                    "p_column_name": "cm_accrual",
                                    "p_datatype": "character varying",
                                    "p_length": 2,
                                    "p_precision": null,
                                    "p_scale": null,
                                    "p_is_primary_key": false,
                                    "p_isautogenerated": "NO",
                                    "p_ordinal_position": 4,
                                    "p_nullable": "YES"
                                },
                                {
                                    "p_inserted_by": 1,
                                    "p_modified_by": 1,
                                    "p_column_name": "npa_date",
                                    "p_datatype": "timestamp without time zone",
                                    "p_length": null,
                                    "p_precision": null,
                                    "p_scale": null,
                                    "p_is_primary_key": false,
                                    "p_isautogenerated": "NO",
                                    "p_ordinal_position": 5,
                                    "p_nullable": "YES"
                                },
                                {
                                    "p_inserted_by": 1,
                                    "p_modified_by": 1,
                                    "p_column_name": "business_date",
                                    "p_datatype": "timestamp without time zone",
                                    "p_length": null,
                                    "p_precision": null,
                                    "p_scale": null,
                                    "p_is_primary_key": false,
                                    "p_isautogenerated": "NO",
                                    "p_ordinal_position": 6,
                                    "p_nullable": "YES"
                                }
                            ],
                            [
                                {
                                    "p_inserted_by": 1,
                                    "p_modified_by": 1,
                                    "p_column_name": "row_id",
                                    "p_datatype": "numeric",
                                    "p_length": null,
                                    "p_precision": 10,
                                    "p_scale": 0,
                                    "p_is_primary_key": false,
                                    "p_isautogenerated": "NO",
                                    "p_ordinal_position": 1,
                                    "p_nullable": "NO"
                                },
                                {
                                    "p_inserted_by": 1,
                                    "p_modified_by": 1,
                                    "p_column_name": "account_number",
                                    "p_datatype": "numeric",
                                    "p_length": null,
                                    "p_precision": 20,
                                    "p_scale": 0,
                                    "p_is_primary_key": false,
                                    "p_isautogenerated": "NO",
                                    "p_ordinal_position": 2,
                                    "p_nullable": "YES"
                                },
                                {
                                    "p_inserted_by": 1,
                                    "p_modified_by": 1,
                                    "p_column_name": "cbs_restructured_date",
                                    "p_datatype": "character varying",
                                    "p_length": 40,
                                    "p_precision": null,
                                    "p_scale": null,
                                    "p_is_primary_key": false,
                                    "p_isautogenerated": "NO",
                                    "p_ordinal_position": 3,
                                    "p_nullable": "YES"
                                },
                                {
                                    "p_inserted_by": 1,
                                    "p_modified_by": 1,
                                    "p_column_name": "cm_accrual",
                                    "p_datatype": "character varying",
                                    "p_length": 2,
                                    "p_precision": null,
                                    "p_scale": null,
                                    "p_is_primary_key": false,
                                    "p_isautogenerated": "NO",
                                    "p_ordinal_position": 4,
                                    "p_nullable": "YES"
                                },
                                {
                                    "p_inserted_by": 1,
                                    "p_modified_by": 1,
                                    "p_column_name": "npa_date",
                                    "p_datatype": "timestamp without time zone",
                                    "p_length": null,
                                    "p_precision": null,
                                    "p_scale": null,
                                    "p_is_primary_key": false,
                                    "p_isautogenerated": "NO",
                                    "p_ordinal_position": 5,
                                    "p_nullable": "YES"
                                },
                                {
                                    "p_inserted_by": 1,
                                    "p_modified_by": 1,
                                    "p_column_name": "business_date",
                                    "p_datatype": "timestamp without time zone",
                                    "p_length": null,
                                    "p_precision": null,
                                    "p_scale": null,
                                    "p_is_primary_key": false,
                                    "p_isautogenerated": "NO",
                                    "p_ordinal_position": 6,
                                    "p_nullable": "YES"
                                }
                            ]
                        ],
                        [
                            [
                                {
                                    "p_inserted_by": 1,
                                    "p_modified_by": 1,
                                    "p_column_name": "row_id",
                                    "p_datatype": "numeric",
                                    "p_length": null,
                                    "p_precision": 38,
                                    "p_scale": 0,
                                    "p_is_primary_key": false,
                                    "p_isautogenerated": "NO",
                                    "p_ordinal_position": 1,
                                    "p_nullable": "NO"
                                },
                                {
                                    "p_inserted_by": 1,
                                    "p_modified_by": 1,
                                    "p_column_name": "createddate",
                                    "p_datatype": "timestamp without time zone",
                                    "p_length": null,
                                    "p_precision": null,
                                    "p_scale": null,
                                    "p_is_primary_key": false,
                                    "p_isautogenerated": "NO",
                                    "p_ordinal_position": 2,
                                    "p_nullable": "YES"
                                },
                                {
                                    "p_inserted_by": 1,
                                    "p_modified_by": 1,
                                    "p_column_name": "account_number",
                                    "p_datatype": "character varying",
                                    "p_length": 255,
                                    "p_precision": null,
                                    "p_scale": null,
                                    "p_is_primary_key": false,
                                    "p_isautogenerated": "NO",
                                    "p_ordinal_position": 3,
                                    "p_nullable": "YES"
                                },
                                {
                                    "p_inserted_by": 1,
                                    "p_modified_by": 1,
                                    "p_column_name": "write_off_month",
                                    "p_datatype": "character varying",
                                    "p_length": 255,
                                    "p_precision": null,
                                    "p_scale": null,
                                    "p_is_primary_key": false,
                                    "p_isautogenerated": "NO",
                                    "p_ordinal_position": 4,
                                    "p_nullable": "YES"
                                }
                            ],
                            [
                                {
                                    "p_inserted_by": 1,
                                    "p_modified_by": 1,
                                    "p_column_name": "row_id",
                                    "p_datatype": "numeric",
                                    "p_length": null,
                                    "p_precision": 38,
                                    "p_scale": 0,
                                    "p_is_primary_key": false,
                                    "p_isautogenerated": "NO",
                                    "p_ordinal_position": 1,
                                    "p_nullable": "NO"
                                },
                                {
                                    "p_inserted_by": 1,
                                    "p_modified_by": 1,
                                    "p_column_name": "createddate",
                                    "p_datatype": "timestamp without time zone",
                                    "p_length": null,
                                    "p_precision": null,
                                    "p_scale": null,
                                    "p_is_primary_key": false,
                                    "p_isautogenerated": "NO",
                                    "p_ordinal_position": 2,
                                    "p_nullable": "YES"
                                },
                                {
                                    "p_inserted_by": 1,
                                    "p_modified_by": 1,
                                    "p_column_name": "account_number",
                                    "p_datatype": "character varying",
                                    "p_length": 255,
                                    "p_precision": null,
                                    "p_scale": null,
                                    "p_is_primary_key": false,
                                    "p_isautogenerated": "NO",
                                    "p_ordinal_position": 3,
                                    "p_nullable": "YES"
                                },
                                {
                                    "p_inserted_by": 1,
                                    "p_modified_by": 1,
                                    "p_column_name": "write_off_month",
                                    "p_datatype": "character varying",
                                    "p_length": 255,
                                    "p_precision": null,
                                    "p_scale": null,
                                    "p_is_primary_key": false,
                                    "p_isautogenerated": "NO",
                                    "p_ordinal_position": 4,
                                    "p_nullable": "YES"
                                }
                            ]
                        ]
                    ],
                    "table_mapping": [
                        [
                            {
                                "p_inserted_by": 1,
                                "p_modified_by": 1,
                                "p_source_conn_id": 4,
                                "p_source_db": "JanaBank",
                                "p_source_schema": "public",
                                "p_source_table": "exception_master",
                                "p_source_column": "row_id",
                                "p_source_data_type": "numeric",
                                "p_dest_conn_id": 5,
                                "p_dest_db": "DestinationDB",
                                "p_dest_schema": "source_schema",
                                "p_dest_table": "exception_master",
                                "p_dest_column": "row_id",
                                "p_dest_data_type": "numeric",
                                "p_ordinal_position": 1
                            },
                            {
                                "p_inserted_by": 1,
                                "p_modified_by": 1,
                                "p_source_conn_id": 4,
                                "p_source_db": "JanaBank",
                                "p_source_schema": "public",
                                "p_source_table": "exception_master",
                                "p_source_column": "account_number",
                                "p_source_data_type": "numeric",
                                "p_dest_conn_id": 5,
                                "p_dest_db": "DestinationDB",
                                "p_dest_schema": "source_schema",
                                "p_dest_table": "exception_master",
                                "p_dest_column": "account_number",
                                "p_dest_data_type": "numeric",
                                "p_ordinal_position": 2
                            },
                            {
                                "p_inserted_by": 1,
                                "p_modified_by": 1,
                                "p_source_conn_id": 4,
                                "p_source_db": "JanaBank",
                                "p_source_schema": "public",
                                "p_source_table": "exception_master",
                                "p_source_column": "cbs_restructured_date",
                                "p_source_data_type": "character varying",
                                "p_dest_conn_id": 5,
                                "p_dest_db": "DestinationDB",
                                "p_dest_schema": "source_schema",
                                "p_dest_table": "exception_master",
                                "p_dest_column": "cbs_restructured_date",
                                "p_dest_data_type": "character varying",
                                "p_ordinal_position": 3
                            },
                            {
                                "p_inserted_by": 1,
                                "p_modified_by": 1,
                                "p_source_conn_id": 4,
                                "p_source_db": "JanaBank",
                                "p_source_schema": "public",
                                "p_source_table": "exception_master",
                                "p_source_column": "cm_accrual",
                                "p_source_data_type": "character varying",
                                "p_dest_conn_id": 5,
                                "p_dest_db": "DestinationDB",
                                "p_dest_schema": "source_schema",
                                "p_dest_table": "exception_master",
                                "p_dest_column": "cm_accrual",
                                "p_dest_data_type": "character varying",
                                "p_ordinal_position": 4
                            },
                            {
                                "p_inserted_by": 1,
                                "p_modified_by": 1,
                                "p_source_conn_id": 4,
                                "p_source_db": "JanaBank",
                                "p_source_schema": "public",
                                "p_source_table": "exception_master",
                                "p_source_column": "npa_date",
                                "p_source_data_type": "timestamp without time zone",
                                "p_dest_conn_id": 5,
                                "p_dest_db": "DestinationDB",
                                "p_dest_schema": "source_schema",
                                "p_dest_table": "exception_master",
                                "p_dest_column": "npa_date",
                                "p_dest_data_type": "timestamp without time zone",
                                "p_ordinal_position": 5
                            },
                            {
                                "p_inserted_by": 1,
                                "p_modified_by": 1,
                                "p_source_conn_id": 4,
                                "p_source_db": "JanaBank",
                                "p_source_schema": "public",
                                "p_source_table": "exception_master",
                                "p_source_column": "business_date",
                                "p_source_data_type": "timestamp without time zone",
                                "p_dest_conn_id": 5,
                                "p_dest_db": "DestinationDB",
                                "p_dest_schema": "source_schema",
                                "p_dest_table": "exception_master",
                                "p_dest_column": "business_date",
                                "p_dest_data_type": "timestamp without time zone",
                                "p_ordinal_position": 6
                            }
                        ],
                        [
                            {
                                "p_inserted_by": 1,
                                "p_modified_by": 1,
                                "p_source_conn_id": 4,
                                "p_source_db": "JanaBank",
                                "p_source_schema": "public",
                                "p_source_table": "npa_auto_tech_write_off",
                                "p_source_column": "row_id",
                                "p_source_data_type": "numeric",
                                "p_dest_conn_id": 5,
                                "p_dest_db": "DestinationDB",
                                "p_dest_schema": "source_schema",
                                "p_dest_table": "npa_auto_tech_write_off",
                                "p_dest_column": "row_id",
                                "p_dest_data_type": "numeric",
                                "p_ordinal_position": 1
                            },
                            {
                                "p_inserted_by": 1,
                                "p_modified_by": 1,
                                "p_source_conn_id": 4,
                                "p_source_db": "JanaBank",
                                "p_source_schema": "public",
                                "p_source_table": "npa_auto_tech_write_off",
                                "p_source_column": "createddate",
                                "p_source_data_type": "timestamp without time zone",
                                "p_dest_conn_id": 5,
                                "p_dest_db": "DestinationDB",
                                "p_dest_schema": "source_schema",
                                "p_dest_table": "npa_auto_tech_write_off",
                                "p_dest_column": "createddate",
                                "p_dest_data_type": "timestamp without time zone",
                                "p_ordinal_position": 2
                            },
                            {
                                "p_inserted_by": 1,
                                "p_modified_by": 1,
                                "p_source_conn_id": 4,
                                "p_source_db": "JanaBank",
                                "p_source_schema": "public",
                                "p_source_table": "npa_auto_tech_write_off",
                                "p_source_column": "account_number",
                                "p_source_data_type": "character varying",
                                "p_dest_conn_id": 5,
                                "p_dest_db": "DestinationDB",
                                "p_dest_schema": "source_schema",
                                "p_dest_table": "npa_auto_tech_write_off",
                                "p_dest_column": "account_number",
                                "p_dest_data_type": "character varying",
                                "p_ordinal_position": 3
                            },
                            {
                                "p_inserted_by": 1,
                                "p_modified_by": 1,
                                "p_source_conn_id": 4,
                                "p_source_db": "JanaBank",
                                "p_source_schema": "public",
                                "p_source_table": "npa_auto_tech_write_off",
                                "p_source_column": "write_off_month",
                                "p_source_data_type": "character varying",
                                "p_dest_conn_id": 5,
                                "p_dest_db": "DestinationDB",
                                "p_dest_schema": "source_schema",
                                "p_dest_table": "npa_auto_tech_write_off",
                                "p_dest_column": "write_off_month",
                                "p_dest_data_type": "character varying",
                                "p_ordinal_position": 4
                            }
                        ]
                    ]
                },
                {
                    "steps": {
                        "p_inserted_by": 1,
                        "p_modified_by": 1,
                        "p_process_step_id": 70,
                        "p_process_master_id": 8,
                        "p_sub_process_id": 31,
                        "p_process_step_order": 2,
                        "p_process_step_action": "process-query",
                        "p_process_step_description": "Subprocess 1 description",
                        "p_process_step_query": [
                            "Subprocess 1 query"
                        ],
                        "p_source_conn_id": 5
                    },
                    "create_table": [],
                    "table_config": [],
                    "table_config_details": [],
                    "table_mapping": []
                },
                {
                    "steps": {
                        "p_inserted_by": 1,
                        "p_modified_by": 1,
                        "p_process_step_id": 71,
                        "p_process_master_id": 8,
                        "p_sub_process_id": 31,
                        "p_process_step_order": 3,
                        "p_process_step_action": "export",
                        "p_process_step_description": "export description",
                        "p_process_step_query": [
                            "ex query1",
                            "ex query2"
                        ],
                        "p_source_conn_id": 4
                    },
                    "create_table": [],
                    "table_config": [],
                    "table_config_details": [],
                    "table_mapping": []
                }
            ]
        },
        {
            "subprocess_data": {
                "p_inserted_by": 1,
                "p_modified_by": 1,
                "p_process_master_id": 8,
                "p_sub_process_id": 32,
                "p_sub_process_order": 2,
                "p_sub_process_name": "Sub2"
            },
            "steps": [
                {
                    "steps": {
                        "p_inserted_by": 1,
                        "p_modified_by": 1,
                        "p_process_step_id": 72,
                        "p_process_master_id": 8,
                        "p_sub_process_id": 32,
                        "p_process_step_order": 1,
                        "p_process_step_action": "process-query",
                        "p_process_step_description": "Subprocess 2 description",
                        "p_process_step_query": [
                            "Subprocess 2 query"
                        ],
                        "p_source_conn_id": 6
                    },
                    "create_table": [],
                    "table_config": [],
                    "table_config_details": [],
                    "table_mapping": []
                }
            ]
        }
    ]
}

const mockAPI = {
    process: {
      process_master_id: 8,
      process_master_guid: "01e54ae6-b17f-4f37-b8f1-e3bc72531231",
      inserted_by: 1,
      modified_by: 1,
      inserted_date: "2025-06-26T15:41:06.351001",
      modified_date: "2025-06-26T15:41:06.351001",
      process_name: "Process for Edit",
      is_active: true,
      is_deleted: false,
      process_version: 1,
      rerun: true,
    },
    subprocesses: [
      {
        subprocess_data: {
          sub_process_id: 31,
          sub_process_guid: "d3abebb4-d217-476f-929b-b84fe3adf1df",
          inserted_by: 1,
          modified_by: 1,
          inserted_date: "2025-06-26T15:41:06.503954",
          modified_date: "2025-06-26T15:41:06.503954",
          process_master_id: 8,
          sub_process_order: 1,
          sub_process_name: "Sub1",
          is_active: true,
          is_deleted: false,
        },
        steps: [
          {
            steps: {
              process_step_id: 69,
              process_step_guid: "7c311e4c-b8f8-4ca3-b66f-6784e0b33870",
              inserted_by: 1,
              modified_by: 1,
              inserted_date: "2025-06-26T15:41:06.646289",
              modified_date: "2025-06-26T15:41:06.646289",
              process_master_id: 8,
              sub_process_id: 31,
              process_step_order: 1,
              process_step_query: [],
              process_table_name: null,
              where_clause: null,
              joining_condition: null,
              process_step_action: "import",
              process_select: null,
              update_columns: null,
              insert_columns: null,
              is_active: true,
              is_deleted: false,
              process_step_description: null,
              source_conn_id: 4,
              dest_conn_id: 5,
            },
            create_table: [],
            table_config: [
              [
                {
                  table_config_id: 56,
                  table_config_guid: "04a334c6-8871-4e1b-8503-3107287237bf",
                  inserted_by: 1,
                  modified_by: 1,
                  inserted_date: "2025-06-26T15:41:06.794041",
                  modified_date: "2025-06-26T15:41:06.794041",
                  process_step_id: 69,
                  data_source_id: 4,
                  schema_name: "public",
                  table_name: "exception_master",
                  is_temporary_table: false,
                  table_type: "source",
                  table_category: "import",
                  is_partitioning: false,
                  is_column_store: false,
                  is_reload: false,
                  is_incremental_load: false,
                  database_name: "JanaBank",
                  is_imported: false,
                  is_exported: false,
                  is_active: true,
                  is_deleted: false,
                  is_upsert: false,
                },
                {
                  table_config_id: 57,
                  table_config_guid: "7c5541c9-2ec9-4432-b4a1-215fc290ff75",
                  inserted_by: 1,
                  modified_by: 1,
                  inserted_date: "2025-06-26T15:41:06.924119",
                  modified_date: "2025-06-26T15:41:06.924119",
                  process_step_id: 69,
                  data_source_id: 5,
                  schema_name: "source_schema",
                  table_name: "exception_master",
                  is_temporary_table: false,
                  table_type: "destination",
                  table_category: "import",
                  is_partitioning: false,
                  is_column_store: false,
                  is_reload: false,
                  is_incremental_load: false,
                  database_name: "DestinationDB",
                  is_imported: false,
                  is_exported: false,
                  is_active: true,
                  is_deleted: false,
                  is_upsert: true,
                },
              ],
              [
                {
                  table_config_id: 58,
                  table_config_guid: "07152567-10ba-4068-b7ae-e49a929a541a",
                  inserted_by: 1,
                  modified_by: 1,
                  inserted_date: "2025-06-26T15:41:07.047289",
                  modified_date: "2025-06-26T15:41:07.047289",
                  process_step_id: 69,
                  data_source_id: 4,
                  schema_name: "public",
                  table_name: "npa_auto_tech_write_off",
                  is_temporary_table: false,
                  table_type: "source",
                  table_category: "import",
                  is_partitioning: false,
                  is_column_store: false,
                  is_reload: false,
                  is_incremental_load: false,
                  database_name: "JanaBank",
                  is_imported: false,
                  is_exported: false,
                  is_active: true,
                  is_deleted: false,
                  is_upsert: false,
                },
                {
                  table_config_id: 59,
                  table_config_guid: "c8ec80bd-e752-4cec-be23-8cc355ab2644",
                  inserted_by: 1,
                  modified_by: 1,
                  inserted_date: "2025-06-26T15:41:07.198508",
                  modified_date: "2025-06-26T15:41:07.198508",
                  process_step_id: 69,
                  data_source_id: 5,
                  schema_name: "source_schema",
                  table_name: "npa_auto_tech_write_off",
                  is_temporary_table: false,
                  table_type: "destination",
                  table_category: "import",
                  is_partitioning: false,
                  is_column_store: false,
                  is_reload: false,
                  is_incremental_load: false,
                  database_name: "DestinationDB",
                  is_imported: false,
                  is_exported: false,
                  is_active: true,
                  is_deleted: false,
                  is_upsert: true,
                },
              ],
            ],
            table_config_details: [
              [
                [
                  {
                    table_config_detail_id: 967,
                    table_config_detail_guid:
                      "3e8a7420-56c6-4f93-8071-3ae85f312b7c",
                    inserted_by: 1,
                    modified_by: 1,
                    inserted_date: "2025-06-26T15:41:07.328678",
                    modified_date: "2025-06-26T15:41:07.328678",
                    process_step_id: 69,
                    table_config_id: 56,
                    column_name: "row_id",
                    datatype: "numeric",
                    length: null,
                    precision: 10,
                    scale: 0,
                    is_primary_key: false,
                    is_autogenerated: false,
                    ordinal_position: 1,
                    nullable: false,
                    is_deleted: false,
                    is_active: true,
                  },
                  {
                    table_config_detail_id: 968,
                    table_config_detail_guid:
                      "f625be8c-169d-4878-9cea-68d7296e540b",
                    inserted_by: 1,
                    modified_by: 1,
                    inserted_date: "2025-06-26T15:41:07.478006",
                    modified_date: "2025-06-26T15:41:07.478006",
                    process_step_id: 69,
                    table_config_id: 56,
                    column_name: "account_number",
                    datatype: "numeric",
                    length: null,
                    precision: 20,
                    scale: 0,
                    is_primary_key: false,
                    is_autogenerated: false,
                    ordinal_position: 2,
                    nullable: true,
                    is_deleted: false,
                    is_active: true,
                  },
                  {
                    table_config_detail_id: 969,
                    table_config_detail_guid:
                      "3b392ec4-f0ba-4eac-8dc2-43a9718f1ab3",
                    inserted_by: 1,
                    modified_by: 1,
                    inserted_date: "2025-06-26T15:41:07.618864",
                    modified_date: "2025-06-26T15:41:07.618864",
                    process_step_id: 69,
                    table_config_id: 56,
                    column_name: "cbs_restructured_date",
                    datatype: "character varying",
                    length: 40,
                    precision: null,
                    scale: null,
                    is_primary_key: false,
                    is_autogenerated: false,
                    ordinal_position: 3,
                    nullable: true,
                    is_deleted: false,
                    is_active: true,
                  },
                  {
                    table_config_detail_id: 970,
                    table_config_detail_guid:
                      "d111988c-289a-435c-9c93-6c8e7b19d1c3",
                    inserted_by: 1,
                    modified_by: 1,
                    inserted_date: "2025-06-26T15:41:07.729903",
                    modified_date: "2025-06-26T15:41:07.729903",
                    process_step_id: 69,
                    table_config_id: 56,
                    column_name: "cm_accrual",
                    datatype: "character varying",
                    length: 2,
                    precision: null,
                    scale: null,
                    is_primary_key: false,
                    is_autogenerated: false,
                    ordinal_position: 4,
                    nullable: true,
                    is_deleted: false,
                    is_active: true,
                  },
                  {
                    table_config_detail_id: 971,
                    table_config_detail_guid:
                      "48a0c497-53d2-43d1-9ef5-ddfb9c610dcf",
                    inserted_by: 1,
                    modified_by: 1,
                    inserted_date: "2025-06-26T15:41:07.866655",
                    modified_date: "2025-06-26T15:41:07.866655",
                    process_step_id: 69,
                    table_config_id: 56,
                    column_name: "npa_date",
                    datatype: "timestamp without time zone",
                    length: null,
                    precision: null,
                    scale: null,
                    is_primary_key: false,
                    is_autogenerated: false,
                    ordinal_position: 5,
                    nullable: true,
                    is_deleted: false,
                    is_active: true,
                  },
                  {
                    table_config_detail_id: 972,
                    table_config_detail_guid:
                      "3f0ab40c-a58b-446c-be62-507c60cd322d",
                    inserted_by: 1,
                    modified_by: 1,
                    inserted_date: "2025-06-26T15:41:07.993301",
                    modified_date: "2025-06-26T15:41:07.993301",
                    process_step_id: 69,
                    table_config_id: 56,
                    column_name: "business_date",
                    datatype: "timestamp without time zone",
                    length: null,
                    precision: null,
                    scale: null,
                    is_primary_key: false,
                    is_autogenerated: false,
                    ordinal_position: 6,
                    nullable: true,
                    is_deleted: false,
                    is_active: true,
                  },
                ],
                [
                  {
                    table_config_detail_id: 973,
                    table_config_detail_guid:
                      "36048425-3c13-43e2-9949-d0b122a786fc",
                    inserted_by: 1,
                    modified_by: 1,
                    inserted_date: "2025-06-26T15:41:08.127804",
                    modified_date: "2025-06-26T15:41:08.127804",
                    process_step_id: 69,
                    table_config_id: 57,
                    column_name: "row_id",
                    datatype: "numeric",
                    length: null,
                    precision: 10,
                    scale: 0,
                    is_primary_key: false,
                    is_autogenerated: false,
                    ordinal_position: 1,
                    nullable: false,
                    is_deleted: false,
                    is_active: true,
                  },
                  {
                    table_config_detail_id: 974,
                    table_config_detail_guid:
                      "6da80f80-0bf9-4359-beb5-0cb09e4a9322",
                    inserted_by: 1,
                    modified_by: 1,
                    inserted_date: "2025-06-26T15:41:08.261619",
                    modified_date: "2025-06-26T15:41:08.261619",
                    process_step_id: 69,
                    table_config_id: 57,
                    column_name: "account_number",
                    datatype: "numeric",
                    length: null,
                    precision: 20,
                    scale: 0,
                    is_primary_key: false,
                    is_autogenerated: false,
                    ordinal_position: 2,
                    nullable: true,
                    is_deleted: false,
                    is_active: true,
                  },
                  {
                    table_config_detail_id: 975,
                    table_config_detail_guid:
                      "8b1b1182-c3b2-48e9-9d5f-641348963fb4",
                    inserted_by: 1,
                    modified_by: 1,
                    inserted_date: "2025-06-26T15:41:08.400908",
                    modified_date: "2025-06-26T15:41:08.400908",
                    process_step_id: 69,
                    table_config_id: 57,
                    column_name: "cbs_restructured_date",
                    datatype: "character varying",
                    length: 40,
                    precision: null,
                    scale: null,
                    is_primary_key: false,
                    is_autogenerated: false,
                    ordinal_position: 3,
                    nullable: true,
                    is_deleted: false,
                    is_active: true,
                  },
                  {
                    table_config_detail_id: 976,
                    table_config_detail_guid:
                      "5873cb0b-fb06-454d-aef1-e9a68829abf7",
                    inserted_by: 1,
                    modified_by: 1,
                    inserted_date: "2025-06-26T15:41:08.535501",
                    modified_date: "2025-06-26T15:41:08.535501",
                    process_step_id: 69,
                    table_config_id: 57,
                    column_name: "cm_accrual",
                    datatype: "character varying",
                    length: 2,
                    precision: null,
                    scale: null,
                    is_primary_key: false,
                    is_autogenerated: false,
                    ordinal_position: 4,
                    nullable: true,
                    is_deleted: false,
                    is_active: true,
                  },
                  {
                    table_config_detail_id: 977,
                    table_config_detail_guid:
                      "f353b809-655c-4f3c-ad8e-6d5e6cc81618",
                    inserted_by: 1,
                    modified_by: 1,
                    inserted_date: "2025-06-26T15:41:08.676859",
                    modified_date: "2025-06-26T15:41:08.676859",
                    process_step_id: 69,
                    table_config_id: 57,
                    column_name: "npa_date",
                    datatype: "timestamp without time zone",
                    length: null,
                    precision: null,
                    scale: null,
                    is_primary_key: false,
                    is_autogenerated: false,
                    ordinal_position: 5,
                    nullable: true,
                    is_deleted: false,
                    is_active: true,
                  },
                  {
                    table_config_detail_id: 978,
                    table_config_detail_guid:
                      "471567ec-8df4-4789-8a89-ff7ee2751806",
                    inserted_by: 1,
                    modified_by: 1,
                    inserted_date: "2025-06-26T15:41:08.843762",
                    modified_date: "2025-06-26T15:41:08.843762",
                    process_step_id: 69,
                    table_config_id: 57,
                    column_name: "business_date",
                    datatype: "timestamp without time zone",
                    length: null,
                    precision: null,
                    scale: null,
                    is_primary_key: false,
                    is_autogenerated: false,
                    ordinal_position: 6,
                    nullable: true,
                    is_deleted: false,
                    is_active: true,
                  },
                ],
              ],
              [
                [
                  {
                    table_config_detail_id: 979,
                    table_config_detail_guid:
                      "b53c76d3-21a6-4d7f-907b-bdebdaea5342",
                    inserted_by: 1,
                    modified_by: 1,
                    inserted_date: "2025-06-26T15:41:09.000962",
                    modified_date: "2025-06-26T15:41:09.000962",
                    process_step_id: 69,
                    table_config_id: 58,
                    column_name: "row_id",
                    datatype: "numeric",
                    length: null,
                    precision: 38,
                    scale: 0,
                    is_primary_key: false,
                    is_autogenerated: false,
                    ordinal_position: 1,
                    nullable: false,
                    is_deleted: false,
                    is_active: true,
                  },
                  {
                    table_config_detail_id: 980,
                    table_config_detail_guid:
                      "2246863b-afd5-4379-add3-5cefd6e01d01",
                    inserted_by: 1,
                    modified_by: 1,
                    inserted_date: "2025-06-26T15:41:09.179677",
                    modified_date: "2025-06-26T15:41:09.179677",
                    process_step_id: 69,
                    table_config_id: 58,
                    column_name: "createddate",
                    datatype: "timestamp without time zone",
                    length: null,
                    precision: null,
                    scale: null,
                    is_primary_key: false,
                    is_autogenerated: false,
                    ordinal_position: 2,
                    nullable: true,
                    is_deleted: false,
                    is_active: true,
                  },
                  {
                    table_config_detail_id: 981,
                    table_config_detail_guid:
                      "11a78615-31c1-4ee6-b2c2-a4a9b1d79662",
                    inserted_by: 1,
                    modified_by: 1,
                    inserted_date: "2025-06-26T15:41:09.321223",
                    modified_date: "2025-06-26T15:41:09.321223",
                    process_step_id: 69,
                    table_config_id: 58,
                    column_name: "account_number",
                    datatype: "character varying",
                    length: 255,
                    precision: null,
                    scale: null,
                    is_primary_key: false,
                    is_autogenerated: false,
                    ordinal_position: 3,
                    nullable: true,
                    is_deleted: false,
                    is_active: true,
                  },
                  {
                    table_config_detail_id: 982,
                    table_config_detail_guid:
                      "cbfadff3-417d-4485-8215-a3638db8f762",
                    inserted_by: 1,
                    modified_by: 1,
                    inserted_date: "2025-06-26T15:41:09.495946",
                    modified_date: "2025-06-26T15:41:09.495946",
                    process_step_id: 69,
                    table_config_id: 58,
                    column_name: "write_off_month",
                    datatype: "character varying",
                    length: 255,
                    precision: null,
                    scale: null,
                    is_primary_key: false,
                    is_autogenerated: false,
                    ordinal_position: 4,
                    nullable: true,
                    is_deleted: false,
                    is_active: true,
                  },
                ],
                [
                  {
                    table_config_detail_id: 983,
                    table_config_detail_guid:
                      "1d032324-7d76-4265-b9cc-233692996b36",
                    inserted_by: 1,
                    modified_by: 1,
                    inserted_date: "2025-06-26T15:41:09.649660",
                    modified_date: "2025-06-26T15:41:09.649660",
                    process_step_id: 69,
                    table_config_id: 59,
                    column_name: "row_id",
                    datatype: "numeric",
                    length: null,
                    precision: 38,
                    scale: 0,
                    is_primary_key: false,
                    is_autogenerated: false,
                    ordinal_position: 1,
                    nullable: false,
                    is_deleted: false,
                    is_active: true,
                  },
                  {
                    table_config_detail_id: 984,
                    table_config_detail_guid:
                      "cf384a33-ceb7-40a6-a9ad-c766e2155b2b",
                    inserted_by: 1,
                    modified_by: 1,
                    inserted_date: "2025-06-26T15:41:09.783100",
                    modified_date: "2025-06-26T15:41:09.783100",
                    process_step_id: 69,
                    table_config_id: 59,
                    column_name: "createddate",
                    datatype: "timestamp without time zone",
                    length: null,
                    precision: null,
                    scale: null,
                    is_primary_key: false,
                    is_autogenerated: false,
                    ordinal_position: 2,
                    nullable: true,
                    is_deleted: false,
                    is_active: true,
                  },
                  {
                    table_config_detail_id: 985,
                    table_config_detail_guid:
                      "52b8a8e0-e6bc-4807-8b20-a5e3b1c33047",
                    inserted_by: 1,
                    modified_by: 1,
                    inserted_date: "2025-06-26T15:41:09.930746",
                    modified_date: "2025-06-26T15:41:09.930746",
                    process_step_id: 69,
                    table_config_id: 59,
                    column_name: "account_number",
                    datatype: "character varying",
                    length: 255,
                    precision: null,
                    scale: null,
                    is_primary_key: false,
                    is_autogenerated: false,
                    ordinal_position: 3,
                    nullable: true,
                    is_deleted: false,
                    is_active: true,
                  },
                  {
                    table_config_detail_id: 986,
                    table_config_detail_guid:
                      "f6f4d6a2-3fb3-4ec1-a143-e2a72440a65c",
                    inserted_by: 1,
                    modified_by: 1,
                    inserted_date: "2025-06-26T15:41:10.087863",
                    modified_date: "2025-06-26T15:41:10.087863",
                    process_step_id: 69,
                    table_config_id: 59,
                    column_name: "write_off_month",
                    datatype: "character varying",
                    length: 255,
                    precision: null,
                    scale: null,
                    is_primary_key: false,
                    is_autogenerated: false,
                    ordinal_position: 4,
                    nullable: true,
                    is_deleted: false,
                    is_active: true,
                  },
                ],
              ],
            ],
            table_mapping: [
              [
                {
                  table_mapping_id: 484,
                  table_mapping_guid: "0da07028-86dc-4827-bda6-ab22e3306bb3",
                  inserted_by: 1,
                  modified_by: 1,
                  inserted_date: "2025-06-26T15:41:10.211187",
                  modified_date: "2025-06-26T15:41:10.211187",
                  process_step_id: 69,
                  source_conn_id: 4,
                  source_db: "JanaBank",
                  source_schema: "public",
                  source_table: "exception_master",
                  source_column: "row_id",
                  source_data_type: "numeric",
                  dest_conn_id: 5,
                  dest_db: "DestinationDB",
                  dest_schema: "source_schema",
                  dest_table: "exception_master",
                  dest_column: "row_id",
                  dest_data_type: "numeric",
                  ordinal_position: 1,
                  is_active: true,
                  is_deleted: false,
                },
                {
                  table_mapping_id: 485,
                  table_mapping_guid: "c74320fb-638a-48f1-9760-d989be5f505f",
                  inserted_by: 1,
                  modified_by: 1,
                  inserted_date: "2025-06-26T15:41:10.356740",
                  modified_date: "2025-06-26T15:41:10.356740",
                  process_step_id: 69,
                  source_conn_id: 4,
                  source_db: "JanaBank",
                  source_schema: "public",
                  source_table: "exception_master",
                  source_column: "account_number",
                  source_data_type: "numeric",
                  dest_conn_id: 5,
                  dest_db: "DestinationDB",
                  dest_schema: "source_schema",
                  dest_table: "exception_master",
                  dest_column: "account_number",
                  dest_data_type: "numeric",
                  ordinal_position: 2,
                  is_active: true,
                  is_deleted: false,
                },
                {
                  table_mapping_id: 486,
                  table_mapping_guid: "dbb5d3fd-baaa-44bc-a00f-6975ec9602a4",
                  inserted_by: 1,
                  modified_by: 1,
                  inserted_date: "2025-06-26T15:41:10.518855",
                  modified_date: "2025-06-26T15:41:10.518855",
                  process_step_id: 69,
                  source_conn_id: 4,
                  source_db: "JanaBank",
                  source_schema: "public",
                  source_table: "exception_master",
                  source_column: "cbs_restructured_date",
                  source_data_type: "character varying",
                  dest_conn_id: 5,
                  dest_db: "DestinationDB",
                  dest_schema: "source_schema",
                  dest_table: "exception_master",
                  dest_column: "cbs_restructured_date",
                  dest_data_type: "character varying",
                  ordinal_position: 3,
                  is_active: true,
                  is_deleted: false,
                },
                {
                  table_mapping_id: 487,
                  table_mapping_guid: "b911aee5-88f4-4718-8bd6-3bdaa62ca240",
                  inserted_by: 1,
                  modified_by: 1,
                  inserted_date: "2025-06-26T15:41:10.638233",
                  modified_date: "2025-06-26T15:41:10.638233",
                  process_step_id: 69,
                  source_conn_id: 4,
                  source_db: "JanaBank",
                  source_schema: "public",
                  source_table: "exception_master",
                  source_column: "cm_accrual",
                  source_data_type: "character varying",
                  dest_conn_id: 5,
                  dest_db: "DestinationDB",
                  dest_schema: "source_schema",
                  dest_table: "exception_master",
                  dest_column: "cm_accrual",
                  dest_data_type: "character varying",
                  ordinal_position: 4,
                  is_active: true,
                  is_deleted: false,
                },
                {
                  table_mapping_id: 488,
                  table_mapping_guid: "20ea5631-66c3-4657-a748-454ff67090b5",
                  inserted_by: 1,
                  modified_by: 1,
                  inserted_date: "2025-06-26T15:41:10.750090",
                  modified_date: "2025-06-26T15:41:10.750090",
                  process_step_id: 69,
                  source_conn_id: 4,
                  source_db: "JanaBank",
                  source_schema: "public",
                  source_table: "exception_master",
                  source_column: "npa_date",
                  source_data_type: "timestamp without time zone",
                  dest_conn_id: 5,
                  dest_db: "DestinationDB",
                  dest_schema: "source_schema",
                  dest_table: "exception_master",
                  dest_column: "npa_date",
                  dest_data_type: "timestamp without time zone",
                  ordinal_position: 5,
                  is_active: true,
                  is_deleted: false,
                },
                {
                  table_mapping_id: 489,
                  table_mapping_guid: "fbc8522e-4b02-4900-9f25-757b7cfc523a",
                  inserted_by: 1,
                  modified_by: 1,
                  inserted_date: "2025-06-26T15:41:10.885672",
                  modified_date: "2025-06-26T15:41:10.885672",
                  process_step_id: 69,
                  source_conn_id: 4,
                  source_db: "JanaBank",
                  source_schema: "public",
                  source_table: "exception_master",
                  source_column: "business_date",
                  source_data_type: "timestamp without time zone",
                  dest_conn_id: 5,
                  dest_db: "DestinationDB",
                  dest_schema: "source_schema",
                  dest_table: "exception_master",
                  dest_column: "business_date",
                  dest_data_type: "timestamp without time zone",
                  ordinal_position: 6,
                  is_active: true,
                  is_deleted: false,
                },
              ],
              [
                {
                  table_mapping_id: 490,
                  table_mapping_guid: "b2b127bd-9820-4c93-94c7-52581bfa1d6b",
                  inserted_by: 1,
                  modified_by: 1,
                  inserted_date: "2025-06-26T15:41:11.062783",
                  modified_date: "2025-06-26T15:41:11.062783",
                  process_step_id: 69,
                  source_conn_id: 4,
                  source_db: "JanaBank",
                  source_schema: "public",
                  source_table: "npa_auto_tech_write_off",
                  source_column: "row_id",
                  source_data_type: "numeric",
                  dest_conn_id: 5,
                  dest_db: "DestinationDB",
                  dest_schema: "source_schema",
                  dest_table: "npa_auto_tech_write_off",
                  dest_column: "row_id",
                  dest_data_type: "numeric",
                  ordinal_position: 1,
                  is_active: true,
                  is_deleted: false,
                },
                {
                  table_mapping_id: 491,
                  table_mapping_guid: "22076a2f-e002-443a-a44b-d46f5f2ba635",
                  inserted_by: 1,
                  modified_by: 1,
                  inserted_date: "2025-06-26T15:41:11.178898",
                  modified_date: "2025-06-26T15:41:11.178898",
                  process_step_id: 69,
                  source_conn_id: 4,
                  source_db: "JanaBank",
                  source_schema: "public",
                  source_table: "npa_auto_tech_write_off",
                  source_column: "createddate",
                  source_data_type: "timestamp without time zone",
                  dest_conn_id: 5,
                  dest_db: "DestinationDB",
                  dest_schema: "source_schema",
                  dest_table: "npa_auto_tech_write_off",
                  dest_column: "createddate",
                  dest_data_type: "timestamp without time zone",
                  ordinal_position: 2,
                  is_active: true,
                  is_deleted: false,
                },
                {
                  table_mapping_id: 492,
                  table_mapping_guid: "ea6d9f9d-200a-452e-b0ef-cc22849a158c",
                  inserted_by: 1,
                  modified_by: 1,
                  inserted_date: "2025-06-26T15:41:11.281585",
                  modified_date: "2025-06-26T15:41:11.281585",
                  process_step_id: 69,
                  source_conn_id: 4,
                  source_db: "JanaBank",
                  source_schema: "public",
                  source_table: "npa_auto_tech_write_off",
                  source_column: "account_number",
                  source_data_type: "character varying",
                  dest_conn_id: 5,
                  dest_db: "DestinationDB",
                  dest_schema: "source_schema",
                  dest_table: "npa_auto_tech_write_off",
                  dest_column: "account_number",
                  dest_data_type: "character varying",
                  ordinal_position: 3,
                  is_active: true,
                  is_deleted: false,
                },
                {
                  table_mapping_id: 493,
                  table_mapping_guid: "8e6e30b4-3775-4fd9-a629-c0fb859021b6",
                  inserted_by: 1,
                  modified_by: 1,
                  inserted_date: "2025-06-26T15:41:11.411494",
                  modified_date: "2025-06-26T15:41:11.411494",
                  process_step_id: 69,
                  source_conn_id: 4,
                  source_db: "JanaBank",
                  source_schema: "public",
                  source_table: "npa_auto_tech_write_off",
                  source_column: "write_off_month",
                  source_data_type: "character varying",
                  dest_conn_id: 5,
                  dest_db: "DestinationDB",
                  dest_schema: "source_schema",
                  dest_table: "npa_auto_tech_write_off",
                  dest_column: "write_off_month",
                  dest_data_type: "character varying",
                  ordinal_position: 4,
                  is_active: true,
                  is_deleted: false,
                },
              ],
            ],
          },
          {
            steps: {
              process_step_id: 70,
              process_step_guid: "5a7af963-fb57-4b29-8c2d-7bba6faea97a",
              inserted_by: 1,
              modified_by: 1,
              inserted_date: "2025-06-26T15:41:11.557998",
              modified_date: "2025-06-26T15:41:11.557998",
              process_master_id: 8,
              sub_process_id: 31,
              process_step_order: 2,
              process_step_query: ["Subprocess 1 query"],
              process_table_name: null,
              where_clause: null,
              joining_condition: null,
              process_step_action: "process-query",
              process_select: null,
              update_columns: null,
              insert_columns: null,
              is_active: true,
              is_deleted: false,
              process_step_description: "Subprocess 1 description",
              source_conn_id: 5,
              dest_conn_id: null,
            },
            create_table: [],
            table_config: [],
            table_config_details: [],
            table_mapping: [],
          },
          {
            steps: {
              process_step_id: 71,
              process_step_guid: "f757dc87-556f-4248-b12d-7bad160a9451",
              inserted_by: 1,
              modified_by: 1,
              inserted_date: "2025-06-26T15:41:11.709142",
              modified_date: "2025-06-26T15:41:11.709142",
              process_master_id: 8,
              sub_process_id: 31,
              process_step_order: 3,
              process_step_query: ["ex query1", "ex query2"],
              process_table_name: null,
              where_clause: null,
              joining_condition: null,
              process_step_action: "export",
              process_select: null,
              update_columns: null,
              insert_columns: null,
              is_active: true,
              is_deleted: false,
              process_step_description: "export description",
              source_conn_id: 4,
              dest_conn_id: null,
            },
            create_table: [],
            table_config: [],
            table_config_details: [],
            table_mapping: [],
          },
        ],
      },
      {
        subprocess_data: {
          sub_process_id: 32,
          sub_process_guid: "51f5ae90-c05b-495a-b348-e21752ce48dd",
          inserted_by: 1,
          modified_by: 1,
          inserted_date: "2025-06-26T15:41:11.811824",
          modified_date: "2025-06-26T15:41:11.811824",
          process_master_id: 8,
          sub_process_order: 2,
          sub_process_name: "Sub2",
          is_active: true,
          is_deleted: false,
        },
        steps: [
          {
            steps: {
              process_step_id: 72,
              process_step_guid: "0ac070b5-9529-43cd-971f-9086da5382d8",
              inserted_by: 1,
              modified_by: 1,
              inserted_date: "2025-06-26T15:41:11.915566",
              modified_date: "2025-06-26T15:41:11.915566",
              process_master_id: 8,
              sub_process_id: 32,
              process_step_order: 1,
              process_step_query: ["Subprocess 2 query"],
              process_table_name: null,
              where_clause: null,
              joining_condition: null,
              process_step_action: "process-query",
              process_select: null,
              update_columns: null,
              insert_columns: null,
              is_active: true,
              is_deleted: false,
              process_step_description: "Subprocess 2 description",
              source_conn_id: 6,
              dest_conn_id: null,
            },
            create_table: [],
            table_config: [],
            table_config_details: [],
            table_mapping: [],
          },
        ],
      },
    ],
  }


const new1 = {
    "process": {
        "p_inserted_by": 1,
        "p_modified_by": 1,
        "p_process_master_id": 9,
        "p_process_name": "Edit Process",
        "p_process_version": 1,
        "p_rerun": true
    },
    "subprocesses": [
        {
            "subprocess_data": {
                "p_sub_process_id": 33,
                "p_is_deleted": true
            }
        },
        {
            "subprocess_data": {
                "p_inserted_by": 1,
                "p_modified_by": 1,
                "p_process_master_id": 9,
                "p_sub_process_id": 34,
                "p_sub_process_order": 1,
                "p_sub_process_name": "Sub2",
                "p_is_deleted": false
            },
            "steps": [
                {
                    "steps": {
                        "p_inserted_by": 1,
                        "p_modified_by": 1,
                        "p_process_step_id": 77,
                        "p_process_master_id": 9,
                        "p_sub_process_id": 34,
                        "p_process_step_order": 1,
                        "p_process_step_action": "process-query",
                        "p_process_step_description": "Subprocess 2 description",
                        "p_process_step_query": [
                            "Subprocess 2 query"
                        ],
                        "p_source_conn_id": 6,
                        "p_is_deleted": false
                    },
                    "create_table": [],
                    "table_config": [],
                    "table_config_details": [],
                    "table_mapping": []
                }
            ]
        }
    ]
}