import HomePage from "./home/page";
import { Button } from "@/components/ui/button";
import {
  Card,
  CardContent,
  CardDescription,
  CardHeader,
  CardTitle,
} from "@/components/ui/card";
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from "@/components/ui/select";
import { Switch } from "@/components/ui/switch";
import Configurations from "./configurations/page";

export default function Home() {
  return <HomePage />;
}

const temp = {
  process: {
    p_inserted_by: 1,
    p_modified_by: 1,
    p_process_name: "Sales Data ETL Pipeline",
    p_process_version: 1,
    p_rerun: true,
  },
  subprocesses: [
    {
      subprocess_data: {
        p_inserted_by: 1,
        p_modified_by: 1,
        p_sub_process_order: 1,
        p_sub_process_name: "Data Import",
      },
      steps: [
        {
          steps: {
            p_inserted_by: 1,
            p_modified_by: 1,
            p_data_source_id: 13,
            p_process_step_order: 1,
            p_process_step_action: "import",
            p_process_step_description: "Import sales data from source system",
            p_process_step_query:
              "SELECT * FROM sales_raw WHERE date >= '2025-01-01'",
          },
          create_table: [
            {
              table_name: "stock",
              schema_name: "inventory",
              is_table_exist: false,
            },
          ],
          table_config: [
            {
              p_inserted_by: 1,
              p_modified_by: 1,
              p_connection_name: "Sales Inventory Connection",
              p_database_name: "SalesInventory",
              p_schema_name: "inventory",
              p_table_name: "stock",
              p_is_temp_table: false,
              p_table_type: "staging",
              p_table_category: "sales",
              p_is_upsert: true,
            },
            {
              p_inserted_by: 1,
              p_modified_by: 1,
              p_connection_name: "ReportingToolDB",
              p_database_name: "ReportingToolDEV",
              p_schema_name: "destination_schema",
              p_table_name: "stock",
              p_is_temp_table: false,
              p_table_type: "staging",
              p_table_category: "sales",
              p_is_upsert: true,
            },
          ],
          table_config_details: [
            [
              {
                p_inserted_by: 1,
                p_modified_by: 1,
                p_column_name: "id",
                p_datatype: "INTEGER",
                p_length: 0,
                p_precision: 0,
                p_scale: 0,
                p_is_primary_key: true,
                p_isautogenerated: false,
                p_ordinal_position: 1,
                p_nullable: false,
              },
              {
                p_inserted_by: 1,
                p_modified_by: 1,
                p_column_name: "name",
                p_datatype: "Char",
                p_length: 0,
                p_precision: 0,
                p_scale: 0,
                p_is_primary_key: false,
                p_isautogenerated: false,
                p_ordinal_position: 2,
                p_nullable: false,
              },
            ],
            [
              {
                p_inserted_by: 1,
                p_modified_by: 1,
                p_column_name: "id",
                p_datatype: "INTEGER",
                p_length: 0,
                p_precision: 0,
                p_scale: 0,
                p_is_primary_key: true,
                p_isautogenerated: false,
                p_ordinal_position: 1,
                p_nullable: false,
              },
              {
                p_inserted_by: 1,
                p_modified_by: 1,
                p_column_name: "name",
                p_datatype: "Char",
                p_length: 0,
                p_precision: 0,
                p_scale: 0,
                p_is_primary_key: false,
                p_isautogenerated: false,
                p_ordinal_position: 2,
                p_nullable: false,
              },
            ],
          ],
          table_mapping: [
            [
              {
                p_inserted_by: 1,
                p_modified_by: 1,
                p_source_conn_id: 13,
                p_source_db: "ReportingToolDEV",
                p_source_schema: "inventory",
                p_source_table: "stock",
                p_source_column: "id",
                p_source_data_type: "INTEGER",
                p_dest_conn_id: 3,
                p_dest_db: "ReportingToolDEV",
                p_dest_schema: "destination_schema",
                p_dest_table: "stock",
                p_dest_column: "sales_id",
                p_dest_data_type: "INTEGER",
                p_ordinal_position: 1,
              },
              {
                p_inserted_by: 1,
                p_modified_by: 1,
                p_source_conn_id: 13,
                p_source_db: "SalesInventory",
                p_source_schema: "inventory",
                p_source_table: "stock",
                p_source_column: "name",
                p_source_data_type: "Char",
                p_dest_conn_id: 3,
                p_dest_db: "ReportingToolDEV",
                p_dest_schema: "destination_schema",
                p_dest_table: "stock",
                p_dest_column: "stock_name",
                p_dest_data_type: "CHAR",
                p_ordinal_position: 2,
              },
            ],
          ],
        },
      ],
    },
    {
      subprocess_data: {
        p_inserted_by: 1,
        p_modified_by: 1,
        p_sub_process_order: 2,
        p_sub_process_name: "Data Transformation",
      },
      steps: [
        {
          steps: {
            p_inserted_by: 1,
            p_modified_by: 1,
            p_data_source_id: 13,
            p_process_step_order: 1,
            p_process_step_action: "transform",
            p_process_step_description:
              "Transform sales data and apply business rules",
            p_process_step_query:
              "INSERT INTO sales_fact SELECT s.sales_id, s.sale_date, p.product_name, s.quantity, s.amount FROM etl.sales_staging s JOIN dim.products p ON s.product_id = p.product_id",
          },
          create_table: [],
          table_config: [],
          table_config_details: [],
          table_mapping: [],
        },
      ],
    },
    {
      subprocess_data: {
        p_inserted_by: 1,
        p_modified_by: 1,
        p_sub_process_order: 3,
        p_sub_process_name: "Data Export",
      },
      steps: [
        {
          steps: {
            p_inserted_by: 1,
            p_modified_by: 1,
            p_data_source_id: 3,
            p_process_step_order: 1,
            p_process_step_action: "export",
            p_process_step_description:
              "Export transformed data to data warehouse",
            p_process_step_query:
              "SELECT * FROM sales_fact WHERE sale_date >= DATEADD(month, -3, GETDATE())",
          },
          create_table: [],
          table_config: [],
          table_config_details: [],
          table_mapping: [],
        },
      ],
    },
  ],
};
